/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controldeinventariio;

/**
 *
 * @author casa
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMorado = new javax.swing.JPanel();
        panelBlanco = new javax.swing.JPanel();
        lblBienvenidos = new javax.swing.JLabel();
        lblBienvenidos1 = new javax.swing.JLabel();
        lblBienvenidos4 = new javax.swing.JLabel();
        lblBienvenidos5 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        ItemIngresar = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        itemGestiondeInventario = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setName("Inicio"); // NOI18N

        panelMorado.setBackground(new java.awt.Color(51, 0, 102));
        panelMorado.setForeground(new java.awt.Color(102, 0, 204));

        javax.swing.GroupLayout panelMoradoLayout = new javax.swing.GroupLayout(panelMorado);
        panelMorado.setLayout(panelMoradoLayout);
        panelMoradoLayout.setHorizontalGroup(
            panelMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        panelMoradoLayout.setVerticalGroup(
            panelMoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));

        lblBienvenidos.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblBienvenidos.setText("a Inventario");

        lblBienvenidos1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblBienvenidos1.setText("Bienvenidos ");

        lblBienvenidos4.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblBienvenidos4.setText("Ripley");

        lblBienvenidos5.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblBienvenidos5.setText("V.E.S");

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBienvenidos1)
                            .addComponent(lblBienvenidos)))
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblBienvenidos4))
                    .addGroup(panelBlancoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblBienvenidos5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBlancoLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblBienvenidos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenidos4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenidos5)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        menuInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 14))); // NOI18N
        menuInicio.setText("Inicio");

        ItemIngresar.setText("Ingresar a Sistema");
        menuInicio.add(ItemIngresar);

        ItemSalir.setText("Salir");
        menuInicio.add(ItemSalir);

        barraMenu.add(menuInicio);

        menuUsuario.setText("Usuario");

        jMenuItem1.setText("Crear Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem1);

        jMenuItem2.setText("Modificar Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem2);

        jMenuItem3.setText("Eliminar Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem3);

        barraMenu.add(menuUsuario);

        menuInventario.setText("Inventario");

        itemGestiondeInventario.setText("Gestion de Inventario");
        itemGestiondeInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestiondeInventarioActionPerformed(evt);
            }
        });
        menuInventario.add(itemGestiondeInventario);

        barraMenu.add(menuInventario);

        menuReportes.setText("Reportes");

        itemReporte.setText("Generar Reporte");
        itemReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReporteActionPerformed(evt);
            }
        });
        menuReportes.add(itemReporte);

        barraMenu.add(menuReportes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMorado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBlanco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMorado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteActionPerformed
            frmReporte rep= new frmReporte ();
            rep.setVisible(true);        
    }//GEN-LAST:event_itemReporteActionPerformed

    private void itemGestiondeInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestiondeInventarioActionPerformed

    }//GEN-LAST:event_itemGestiondeInventarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            FrmCrearUsuario cu= new FrmCrearUsuario ();
            cu.setVisible(true);               // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            FrmModificarUsuario mu= new FrmModificarUsuario ();
            mu.setVisible(true);       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            FrmEliminarUsuario eu= new FrmEliminarUsuario ();
            eu.setVisible(true);       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemIngresar;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemGestiondeInventario;
    private javax.swing.JMenuItem itemReporte;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblBienvenidos;
    private javax.swing.JLabel lblBienvenidos1;
    private javax.swing.JLabel lblBienvenidos4;
    private javax.swing.JLabel lblBienvenidos5;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPanel panelMorado;
    // End of variables declaration//GEN-END:variables
}
