/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete;

/**
 *
 * @author PC-ELLA
 */
public class ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form ventana2
     */
    public ventana2() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(iconoSeguridad,"src/images/seguridad.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(iconoInventario,"src/images/inventarioIcono.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Notificaciones = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        PanelControl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ProductoA = new javax.swing.JButton();
        ProductoB = new javax.swing.JButton();
        ProductoC = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BarrasColor1 = new javax.swing.JLabel();
        BarrasColor = new javax.swing.JLabel();
        iconoInventario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        GestiónInventarios = new javax.swing.JButton();
        MóduloSeguridad = new javax.swing.JButton();
        iconoSeguridad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        Notificaciones.setBackground(new java.awt.Color(255, 0, 51));
        Notificaciones.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Notificaciones.setForeground(new java.awt.Color(255, 255, 255));
        Notificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Notificaciones.setText("Notificaciones");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Notificaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(Notificaciones)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        PanelControl.setBackground(new java.awt.Color(255, 0, 51));
        PanelControl.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        PanelControl.setForeground(new java.awt.Color(255, 255, 255));
        PanelControl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelControl.setText("Panel de control");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(PanelControl)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButton1.setText("Total de productos: 1500");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Productos más vendidos:");
        jLabel4.setToolTipText("");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, -1));

        ProductoA.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        ProductoA.setText("1. ProductoA");
        ProductoA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProductoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoAActionPerformed(evt);
            }
        });
        jPanel7.add(ProductoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, -1));

        ProductoB.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        ProductoB.setText("2. ProductoB");
        ProductoB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProductoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoBActionPerformed(evt);
            }
        });
        jPanel7.add(ProductoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, -1));

        ProductoC.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        ProductoC.setText("3. ProductoC");
        ProductoC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProductoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoCActionPerformed(evt);
            }
        });
        jPanel7.add(ProductoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 170));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jList1.setBorder(null);
        jList1.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "- El stock de Producto D es bajo.", "- Nueva venta registrada!" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 130));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 180, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Iconousuario.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 102));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User: Admin   ID: #3245  \n");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 500));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarrasColor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BarrasColores_1.png"))); // NOI18N
        BarrasColor1.setAutoscrolls(true);
        jPanel3.add(BarrasColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -70, 20, 500));

        BarrasColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BarrasColores_1.png"))); // NOI18N
        BarrasColor.setAutoscrolls(true);
        jPanel3.add(BarrasColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 20, 500));

        iconoInventario.setToolTipText("");
        jPanel3.add(iconoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 100, 80));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 620, 20));

        GestiónInventarios.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        GestiónInventarios.setText("GESTIÓN DE INVENTARIO"); // NOI18N
        GestiónInventarios.setToolTipText("");
        GestiónInventarios.setAlignmentY(0.0F);
        GestiónInventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestiónInventariosActionPerformed(evt);
            }
        });
        jPanel3.add(GestiónInventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 260, 60));

        MóduloSeguridad.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        MóduloSeguridad.setText("MÓDULO DE SEGURIDAD");
        MóduloSeguridad.setAlignmentY(0.0F);
        MóduloSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MóduloSeguridadActionPerformed(evt);
            }
        });
        jPanel3.add(MóduloSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 220, 60));

        iconoSeguridad.setToolTipText("");
        jPanel3.add(iconoSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 100, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 620, 430));
        jPanel3.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENÚ PRINCIPAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MóduloSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MóduloSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MóduloSeguridadActionPerformed

    private void GestiónInventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestiónInventariosActionPerformed
        VentanaGestiónInventario ventana = new VentanaGestiónInventario();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GestiónInventariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProductoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoBActionPerformed

    private void ProductoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoAActionPerformed

    private void ProductoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarrasColor;
    private javax.swing.JLabel BarrasColor1;
    private javax.swing.JButton GestiónInventarios;
    private javax.swing.JButton MóduloSeguridad;
    private javax.swing.JLabel Notificaciones;
    private javax.swing.JLabel PanelControl;
    private javax.swing.JButton ProductoA;
    private javax.swing.JButton ProductoB;
    private javax.swing.JButton ProductoC;
    private javax.swing.JLabel iconoInventario;
    private javax.swing.JLabel iconoSeguridad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
